name: realworld
parameters:
    filename: ['laptop_prices','Electronic_sales_Sep2023-Sep2024','Ecommerce_Sales_Prediction_Dataset',
                'world_tourism_economy_data']
    filetype: ['csv','csv','csv','csv']